version: '3.9'
services:
  web-site1:
    image: httpd:latest
    container_name: web-site1
    # ports: # commenting ports to make them private so this service can only be reached by nginx proxy
    # - '8000:80'
    volumes:
    - ./app1:/usr/local/apache2/htdocs

  web-site2:
    image: httpd:latest
    container_name: web-site2
    # ports:
    # - '8001:80'
    volumes:
    - ./app2:/usr/local/apache2/htdocs

  api:
    image: node:18
    container_name: api
    working_dir: /home/node/app
    # ports:
    #   - "4000:80"
    command: bash -c "npm ci && node index.js"
    volumes:
      - "./api:/home/node/app"

  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - api
      - web-site1
      - web-site2

